### ISSUE TITLE
Updates to Entities, Bundles, and Fields

### ISSUE THREAD

**Issue by shawnawsu** [tripal/t4d8#1]
Please tag all tickets and pr's with group 1 to denote it relates to this first group of updates.

Files this update will require to be reviewed and updated (in order):

- [ ] Tripal Module
     - [x] Convert tripal.info to tripal.yml
     - [x]  [tripal.module](https://github.com/tripal/t4d8/issues/17)
- [ ] Convert hook_menu and forms
     - [x] hook_menu
     - [x] tripal.admin_files.inc: #23, #24 
     - [n/a] tripal.admin.inc (not needed due to the more independant way cvterms are stored in D8)
- [x] tripal.install #25
- [ ] includes
    - [x] TripalVocab
        - [x] TripalVocab.inc
        - [x] TripalVocabController.inc
        - [x] TripalVocabViewsController.inc
    - [x] TripalTerm
        - [x] TripalTerm.inc
        - [x] TripalTermController.inc
        - [x] TripalTermViewsController.inc
    - [x] TripalEntity
        - [x] TripalEntity.inc
        - [x] tripal.entity.inc (makes reference to bundles but contains functions called by TripalEntityUIController.inc)
        - [x] TripalEntityController.inc
        - [ ] TripalEntityCollection.inc
        - [x] TripalEntityUIController.inc
        - [x] TripalEntityViewsController.inc
    - [x] TripalBundle
        - [x] TripalBundle.inc
        - [x] TripalBundleContoller.inc
        - [x] TripalBundleUIController.inc
        - [x] TripalBundleViewsController.inc
    - [ ] TripalField #28 
        - [ ] Tripalfields
        - [ ] TripalField.inc
        - [ ] TripalFieldFormatter.inc
        - [ ] TripalFieldWidget.inc
        - [ ] CONTENT_TYPE
                - [ ] content_type.inc
        - [ ] RDFS__TYPE
                - [ ] rdfs__type_formatter.inc
                - [ ] rdfs__type_widget.inc
                - [ ] Rdfs__type.inc
        - [ ] TripalFieldDownloaders
                - [ ] TripalCSVDownloader.inc
                - [ ] TripalFieldDownloader.inc
                - [ ] TripalGFF3Downloader.inc
                - [ ] TripalNucFASTADownloader.inc
                - [ ] TripalProteinFASTADownloader.inc
                - [ ] TripalTabDownloader.inc
    - [ ] APIs
        - [x] tripal.terms.api.inc #26
        - [ ] tripal.entities.api.inc #27
        - [ ] tripal.fields.api.inc #28
        - [ ] tripal.fields.inc #28 
        - [ ] tripal.field_storage.inc #28
        - [ ] TripalFieldQuery.inc #28
        - [ ] tripal.term_lookup.inc

**Comment by laceysanderson** [comment]
PR: #10

Files this PR upgrades
 - TripalVocab
    - [x] TripalVocab.inc
    - [x] TripalVocabController.inc (no longer needed)
    - [x] TripalVocabViewsController.inc
 - TripalTerm
    - [ ] tripal.terms.api.inc
    - [x] TripalTerm.inc
    - [x] TripalTermController.inc (no longer needed)
    - [x] TripalTermViewsController.inc

## Method
- TripalVocab & TripalTerm are non-fieldable Drupal Entities.
- No information is stored in Chado and these entities are not connected to chado cv/cvterm as is the case in Tripal 3.x
- I chose not to create view pages as there is not much information on them. Instead all information is on the listing page including links to add/edit/delete
- Both Vocab/Term listings are available through Structure in the admin pages and require 'view administration pages' permission

## Tests
### TripalVocabEntityTest.php:
#### testTripalVocabEntity()
1. Go to Vocab listing as unprivileged user and ensure they get access denied.
2. Login as privileged user; check that "Tripal Controlled Vocabularies" is in the structure listing.
3. Click the link and check it goes to the vocab listing. Also ensure users get a message telling them there is no content yet.
4. Goto the add vocabulary form. Check it has the form fields we expect. Fill it out with a valid unique name and submit. Check for the message indicating the vocab is saved.
5. Go to the Vocab listing. Check there is no message indicating no vocabularies. Also check the name, edit and delete links for the new vocabulary are present in the page.
6. Click the edit link, change the vocabulary name and submit. Check for the message indicating the vocab changes were saved.
7. Go to the Vocab listing. Check the new name, edit and delete links for the changed vocabulary are present in the page. Also check that the old name is not present in the page.
8. Click the delete link and check you get the confirmation page. Leave the delete page without submitting and ensure the vocab wasn't deleted on the listing page.
9. Click delete again. This time confirm delete and check the listing to ensure the vocab is no longer there.

#### testPaths()
For Each route defined for TripalVocab crud ensure a user logged in with a specific set of permissions gets the page status code we expect (i.e. access denied if they don't have sufficient permission and 200 if they do). See `providerTestPaths()` for the list of paths tested.

### TripalTermEntityTest.php:
#### testTripalTermEntity()
1. Go to Term listing as unprivileged user and ensure they get access denied.
2. Login as privileged user; check that "Tripal Controlled Vocabulary Terms" is in the structure listing.
3. Click the link and check it goes to the term listing. Also ensure users get a message telling them there is no content yet.
4. Goto the add vocabulary term form. Check it has the form fields we expect. Fill it out with a valid unique name, accession and newly created vocab and submit. Check for the message indicating the vocab term is saved.
5. Go to the Term listing. Check there is no message indicating no terms. Also check the name, accession, vocab, edit and delete links for the new term are present in the page.
6. Click the edit link, change the term name and submit. Check for the message indicating the term changes were saved.
7. Go to the term listing. Check the new name, old accession, old vocab, edit and delete links for the changed vocabulary are present in the page.
8. Click the delete link and check you get the confirmation page. Leave the delete page without submitting and ensure the term wasn't deleted on the listing page.
9. Click delete again. This time confirm delete and check the listing to ensure the vocab is no longer there.

#### testPaths()
For Each route defined for TripalTerm crud ensure a user logged in with a specific set of permissions gets the page status code we expect (i.e. access denied if they don't have sufficient permission and 200 if they do). See `providerTestPaths()` for the list of paths tested.

**Comment by laceysanderson** [comment]
PR #13 
PR #14
PR #15 

## Tripal Entity Type and Tripal Entity

Tripal content and tripal content types are now fully functional! Additionally, I expanded Tripal Vocab and Tripal Term to include all details needed independent of Chado and added view pages. I l also tested basic views integration and it works!

### Files these PRs upgrade

 - [x] TripalEntity
    - [x] TripalEntity.inc
    - [x] tripal.entity.inc (makes reference to bundles but contains functions called by TripalEntityUIController.inc)
    - [x] TripalEntityController.inc
    - [ ] TripalEntityCollection.inc
    - [x] TripalEntityUIController.inc
    - [x] TripalEntityViewsController.inc
 - [x] TripalBundle
    - [x] TripalBundle.inc
        - [x] TripalBundleContoller.inc
        - [x] TripalBundleUIController.inc
        - [x] TripalBundleViewsController.inc

**Comment by laceysanderson** [comment]
I've gone through and created issues for all the remaining parts of group 1. You can access them [using the group 1 tag](https://github.com/tripal/t4d8/issues?q=is%3Aissue+is%3Aopen+label%3A%22Group+1+-++Entities%7CBundles%7CFields%22) or by checking the main list at the top of this page which I updated with the sub-issues. 

To jump in, mention your intent on one of the sub-issues and once complete, report back here :-) Also if you have any questions or run into any problems feel free to tag me!

**Comment by laceysanderson** [comment]
Closing these roadmap issues as we arn't currently using this approach to focus the upgrade. 

This is part of an attempt to minimize the number of issues in this repo in preparation for moving back to the core tripal/tripal repo.
